name: Test Workflow

on:
  push:
    branches:
      - main  # Ejecuta este flujo en cada push a la rama 'main'

jobs:
  create_directories_and_files:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobar ubicación actual
        run: |
          pwd  # Imprime el directorio actual para verificar dónde se ejecuta

      - name: Crear carpetas y archivos de prueba
        run: |
          # Crear la carpeta principal "test"
          mkdir -p test
          
          # Cambiar al directorio "test"
          cd test
          
          # Crear subcarpetas dentro de "test"
          mkdir -p noticias deportes economia politica
          
          # Crear archivos con contenido de ejemplo usando echo
          echo "Noticia de última hora en deportes: Equipo gana campeonato." > deportes/noticia1.txt
          echo "Análisis del mercado: Economía mundial en crecimiento." > economia/noticia2.txt
          echo "Elecciones: Nuevos cambios en el panorama político." > politica/noticia3.txt
          
          # Volver al directorio principal y listar la estructura creada
          cd ..
          echo "Estructura de carpetas y archivos creados:"
          ls -R test  # Lista de forma recursiva para ver toda la estructura
          
      - name: Mostrar ubicación final y estructura completa
        run: |
          pwd  # Imprime el directorio actual para confirmar ubicación
          ls -R  # Lista todos los archivos y carpetas de forma recursiva desde el directorio actual
